server:
  port: 8081

spring:
  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: 101.200.178.253 # 地址
    port: 6379 # 端口
    database: 0 # 数据库索引
    password: pK8aeEsM260ryincBCAYmWcBSZNJB0jx
